### ISSUE TITLE
Review for https://github.com/openjournals/joss-reviews/issues/185

### ISSUE THREAD

**Issue by daattali** [lebebr01/highlightHTML#5]
The goal of this package is to help users to style tables or text in HTML files. It requires the user to edit the source HTML by adding IDs to cells in a table or to specific text, and then using an R function to assign CSS styles to those IDS. While the package's aim seems useful , I find it somewhat difficult and unintuitive to use in its current form. I think spending some time on improving the documentation and explanations would help a great deal. 

## README comments (difficult to understand and contains many errors)

- First major comment is about clarity and readability of README. After reading the first paragraph, it's not at all clear to me **where** to use this package. Hightlight HTML tables... in shiny? in rmarkdown? Or literally in HTML files, but in that case it seems unrelated to R.

- There are also many typos in the README, missing words, and some awkward sentences. I saw the short `paper.md` file and that reads *great*! But the README, which is what most people will see when they find the package, is hard to understand unfortunately.

- In the first sentence in the Usage section for example: it's not clear to me how you get this table that looks like this -- am I supposed to look at the table's content or how it looks visually? Because of the description of the package, I kept thinking the look of that table is what mattered, but that was wrong.

- After reading the first sentence in "Usage" it's clear this is intended to be used on HTML pages produced from markdown. So that should be made clear in the intro.

- First sentence in usage: how do you get this table that looks like this? (do you mean visually or content-wise?)

- It would be nice to actually show what the input is and how the table looks initially, and then show with an image what the table looks like afterwards. Maybe if some of the wording changed from "table" to "dataframe" it could make it a bit more clear, because the word "table" is being used to describe both a rectangular dataset and the actual visual HTML table in an output. That ambiguity caused me a lot of confusion.

- I would add a note on how to install devtools since devtools is mentioned and people may not have it installed.

- In the example code in the README, the `library(hightlightHTML)` has a typo in the package's name

- When showing the example with the `bgtable.html` file, it would help if you showed us HOW you even created the input html file

- Is it `update_css` or `updateCSS`? Both versions are used in the README

- Why would I ever choose `update_css=FALSE`? 

- Personal opinion: I would not overwrite the input file unless explicitly told so. It could be damaging to try out the function, forget you need to add an output , and lose your original file. Maybe default to <input_filename>-out.html to avoid overwriting the input file?

- The package's DESCRIPTION says it's also a tool to highlight text from an HTML document, but that's not mentioned at all in the entire README. The DESCRIPTION also mentions the ability to compile directly from Rmd but there's no documentation for that either

## Vignette

-The vignette says that it is possible to highlight **any** text, not just HTML tables. So shouldn't the github tagline and the readme update to reflect that?

- `table_id_inject()` is briefly mentioned, which to me seems like an important function because this is an R package and this is the first R package and I still don't understand how to make a basic example in R

- It'd be helpful if you show the input file, because running `file <- system.file(...)` users won't know what's in there. How is the input supposed to look like?

## Code

- Testing seems very light: `test_structure.r` has only one test, and all it looks for is `expect_true(is.character(tmp))`, it's not actually testing the structure. The function could be very wrong and give unexpected results but still pass the test.

- Most internal functions don't use any variable names, just `x` `tmp` `tmpA` `tmpB` etc so it'll be difficult to debug and maintain in the future

- `rgb2hex()`: documentation should say that the first param can be a named list but the second param is an unnamed list

- `rgb2hex()`: No error checking or error handling. Calling `rgb2hex()` results in an obscure unhelpful message `Error in names(tmp) <- namescol : object 'tmp' not found`

- I see a few checks for `if(... & ...)` and I think you probably want to use `&&` instead of `&` (& is for vectorized comparisons, but I think these if statements want a single comparison)

- `table_id_inject`: the first param, x, says "A table object" -- do you mean a data.frame? That should be clarified what a table object is (since the word table is used a lot in this package and means other things). I would also use a better name than `x`

- `conditions`: I don't know what the syntax is or what conditions I can use. Based on the examples I know I can use '< x' or '> x', but can you use `<=`? Do you need to use one or two equals for equality? Can you use any other conditions (string matching? being BETWEEN two numbers?)

---

Overall, while the idea of the package sounds very useful, I'm having a hard time imagining the workflow to use it. If I have an HTML file with some tables in it, I don't see a simple way to modify the tables to include the IDs, and if it's not simple and effortless then I would be very unlikely to use the package.

Feel free to ignore any of the comments, these are obviously just my personal thoughts and it's possible some of them are wrong because of my own misunderstanding!

**Comment by lebebr01** [comment]
Thanks @daattali for the thoughtful comments and suggestions. In general the following aspects have been adjusted based on your comments. The README has been significantly adjusted to better reflect the purpose of the package and more typical use cases. The vignette has also been expanded to discuss the `table_id_inject` function in more detail and the source of the input file is shown. Lastly, the code has been adjusted to help improve debugging (i.e. more informative names internally, `&` changed to `&&` where relevant). More specifics are given below in each of these three areas.

## README

- First 6 bullets are related and bundled here. In general the README has been reworked significantly. The introduction to the package has been clarified and expanded slightly to better discuss what I view is a typical use of the package. Some of this has been borrowed from the paper.md JOSS submission. The trivial example has been replaced with a more typical workflow from Rmd to HTML directly with the functions in the package, this is shown in the section "Simple Example of Package Workflow". In the example, I show the raw input Rmd file, the look of the intermediate markdown table with included CSS ids, and then the final code step to compile the document into an HTML. Finally, a screenshot is included to show the look of the final output. I also attempted to change "table" in a few places to "summary table" to reflect the type of table that I feel should be passed to the `table_id_inject` function. I'd be interested in feedback on whether this is both easier to read and offers a more compelling use/workflow for the package.
- Added line to README about installation of devtools package.
- Fixed `library(hightlightHTML)` typo.
- The example with `bgtable.html` was removed as this was a contrived example, primarily for testing. A newer example from Rmd to HTML was created to reflect the most useful use case for the package. This file is called `joss.Rmd`.
- `update_css = FALSE` is used internally and as such has been removed from the master `highlight_html` function, instead just passed internally to the two `highlight_html_cells` and `highlight_html_text` functions. Discussion of this argument has also been removed from the README and vignette.
- Great suggestion on not overwriting input file. This has been remedied to include a message if the output file location is not specified and the output is then "<input>_out.html". The file path of the generated output file is included in the printed message.
- Updated package DESCRIPTION to better reflect package goals and maintain consistency with README documentation.

## Vignette

- The GitHub tagline has been edited as well as the README to better reflect the scope of the package and typical use case.
- More time in vignette is given to the `table_id_inject` function. 
- Similar to the README, the raw input file is shown for the typical example.

## Code

- Adjusted tests. This is an area I have commonly struggled with implementation. I believe the tests are a bit more helpful to help distinguish whether specific features are working. I am now testing whether the CSS tags and ids are found within the output document. I'm open to any additional tests you think about be useful here.
- Internal names were replaced to more descriptive names to help improve debugging in the future. Very useful suggestion.
- Adjusted `rgb2hex` function documentation to reflect named vs unnamed list specification.
- Added error handling to catch double NULL case for `rgb2hex` function.
- Switched code where relevant to `&&` instead of `&`. I wasn't aware of the difference actually. Thanks for pointing this out.
- Attempted to clarify the input for the `table_id_inject` function to: A summary table object, most commonly will be a data.frame, but can also be a count table using the `table` function. Let me know if this is more clear.
- `conditions`: additional examples are given and added documentation within the details section to operations that are allowed and which are allowed for each type of variable (i.e. which are allowed for numeric vs categorical). 
- Note: I added a rather simple functionality to the `table_id_inject` function. This function now allows for rounding of numeric columns. A by product of the CSS id insertion is that the columns are converted to text. This makes it more difficult to round numeric values to a specific number of decimal places. This feature has been added as an optional argument to the `table_id_inject` function called `num_digits`. This argument takes a single numeric integer that is passed to the `round` function within R.

# Changes
Most of the changes can be found in this commit (to explore changes in more detail): fc1cf86e2aff8a14f986bf9c7520e313611dbc78. A handful of smaller changes were made in the last 4 commits.

Looking forward to your thoughts on the changes, clarity of package usage, and any other comments you think would make the package more useful or clear. Thanks in advance.

**Comment by daattali** [comment]
This version is much better!

A few comments:

- In the README, the command to install the package from devtools is `devtools::install_github('lebebr01/highlightHTMl')` instead of `devtools::install_github('lebebr01/highlightHTML')` (the last "l" in the package name is not capitalized. This will technically still work but probably better to fix it)

- I would put the example of `{#bggrey example}` inside an inline code block, so that it's clear what text exactly is example code vs explanation text.

- I just realized something: CSS IDs are meant to only be applied to one element. IDs are supposed to be unique. But in the examples you show, there are multiple cells that you're giving the same ID to. To me it sounds like a CSS class rather than an ID is more fitting.

- Simple example in the README: It's definitely much better, but it still takes a lot of brain power from the reader to understand what's going on. I think it would make it significantly clearer if you show what the original table looks like, then you say what hashtags you'll add to what cells (for example, say that you'll add "#bgblack" to any cell in the weight column that is larger than 300, #bggrey to any weight over 270, etc) (like the basic example in rmd). The "basic example" in the vignette is great - that's exactly what I'd want to see initially, it explains exactly what the input is, what you need to do , and what the result is

- The arguments to `table_id_inject()` have to be the same length, right? Then there should be some check for that, with an appropriate error message. I tried removing one element from the `variable` list and I got a generic error.

- Testing: much better! I would remove the one test that is commented out, or fix it. And I wouldn't use dplyr inside tests, I would make them as dependency-free as possible, to make sure they only test your code. Unit tests should be as small and independent as possible.

These are all fairly small changes compared to what I reviewed last time, so no need to let me know when you do it, I trust that you'll implement them. The package looks good now :+1:

**Comment by lebebr01** [comment]
Thanks @daattali. I appreciate your comments and you taking the time to look through the package. I'll implement these soon.

Cheers.
